### ISSUE TITLE
[D3 plugin]: shape support for line charts

### ISSUE THREAD

**Issue by kuzmadom** [gravity-ui/chartkit#334]
It can be useful to display multiple measures with different lines. For example, the basic sales targets, optimistic sales targets, and actual sales can be represented as a dotted, dashed, and solid line, respectively.

<img width="658" alt="Снимок экрана 2023-10-24 в 19 35 34" src="https://github.com/gravity-ui/chartkit/assets/7911723/07de7041-c2ed-4289-824f-58fa25e3b82c">

**Comment by korvin89** [comment]
Added here https://github.com/gravity-ui/chartkit/pull/368
