### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by artienn** [gravity-ui/chartkit#344]
Привет!

Пробую запустить код из примера, но не рисуются линии и в консоле ошибка Uncaught TypeError: Cannot read properties of undefined (reading 'call')

Можете подсказать в чем проблема? 

[codesandbox](https://codesandbox.io/p/sandbox/sweet-lederberg-8jjfpf?file=%2Fsrc%2FApp.tsx&embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp1bupp8000a3b6msf6ywmjl%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp1bupp700033b6mtcnf9yc5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp1bupp700073b6mdm81i7hb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp1bupp700093b6mkkkx4s1c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp1bupp700033b6mtcnf9yc5%2522%253A%257B%2522id%2522%253A%2522clp1bupp700033b6mtcnf9yc5%2522%252C%2522activeTabId%2522%253A%2522clp1bvr3100fa3b6mvk0h0naa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1bupp700023b6mobfvpdwu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clp1bvr3100fa3b6mvk0h0naa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fnode_modules%252F%2540gravity-ui%252Fyagr%252Fdist%252FYagrCore%252Ftypes.d.ts%2522%252C%2522id%2522%253A%2522clp1c03v001co3b6mza6xvyan%2522%252C%2522mode%2522%253A%2522temporary%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clp1bupp700093b6mkkkx4s1c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1bupp700083b6m0aa66nkc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp1bupp700093b6mkkkx4s1c%2522%252C%2522activeTabId%2522%253A%2522clp1bupp700083b6m0aa66nkc%2522%257D%252C%2522clp1bupp700073b6mdm81i7hb%2522%253A%257B%2522id%2522%253A%2522clp1bupp700073b6mdm81i7hb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp1bupp700043b6m7tqv240l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clp1bupp700053b6mi18h3ws6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clp1bupp700063b6mladgha6n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522preview%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp1bupp700043b6m7tqv240l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A29.09722222222223%257D)

**Comment by artienn** [comment]
Работает если добавить hooks в libraryConfig

**Comment by korvin89** [comment]
@zefirka

**Comment by korvin89** [comment]
Fixed [here](https://github.com/gravity-ui/yagr/commit/c419cb9119c5cb08057bc02973700ce9acb167e6)
