### ISSUE TITLE
Transparent tooltip legend colors with transparent area

### ISSUE THREAD

**Issue by artemmufazalov** [gravity-ui/chartkit#439]
In our service we want to add grafana-style charts, with `area` type, bright and solid line, but semi-transparent background.

We use `yagr` plugin.

Area color is used in tooltip, so if we make area transparent, color in tooltip becomes transparent as well.

 Example 1:
<img width="889" alt="Screen Shot 2024-02-29 at 19 22 07" src="https://github.com/gravity-ui/chartkit/assets/67755036/91067aa0-91d9-4e26-be9b-af226c425b23">

 Example 2:
<img width="696" alt="Screen Shot 2024-02-29 at 19 21 11" src="https://github.com/gravity-ui/chartkit/assets/67755036/74435549-e945-4d6e-840a-d3d4319aacfb">

**Comment by korvin89** [comment]
@zefirka Hey! Is it possible to get access to the `lineColor` property in `TooltipRenderOptions`?

**Comment by zefirka** [comment]
It's possible having [TooltipRow](https://github.com/gravity-ui/yagr/blob/main/src/YagrCore/plugins/tooltip/types.ts#L167) item in TooltipRenderOptions['scales'][string]['rows'] to use `id` property to get to series config:

```js
const lineColor = tooltipRenderOptions.yagr.getSeriesById(item.id)?.lineColor;
```

**Comment by korvin89** [comment]
@artemmufazalov Hey! I've added a new property [legendColorKey](https://github.com/gravity-ui/chartkit/blob/ae6a00f5751047c7509d8942de28a517d375e255/src/plugins/yagr/types.ts#L26) in versions [4.23.0](https://github.com/gravity-ui/chartkit/releases/tag/v4.23.0) and [5.2.0](https://github.com/gravity-ui/chartkit/releases/tag/v5.2.0). You can check usage example [here](https://github.com/gravity-ui/chartkit/blob/ae6a00f5751047c7509d8942de28a517d375e255/src/plugins/yagr/__stories__/mocks/line10.ts#L121-L149).

**Comment by artemmufazalov** [comment]
Everything works, thanks!
